---
- name: Ensure procps is installed.
  package:
    name: "{{ procps_package }}"
    state: present
  when: >
    ansible_distribution != 'Debian'
    or ansible_distribution_major_version | int < 10

# See: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
- name: Let iptables see bridged traffic.
  shell: |
    cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
    overlay
    br_netfilter
    EOF

    sudo modprobe overlay
    sudo modprobe br_netfilter

    cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-iptables  = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    net.ipv4.ip_forward                 = 1
    EOF

    sudo sysctl --system

  when: >
    ansible_distribution != 'Debian'
    or ansible_distribution_major_version | int < 10

# - name: Let iptables see bridged traffic.
#   sysctl:
#     name: "{{ item }}"
#     value: '1'
#     state: present
#   loop:
#     - net.bridge.bridge-nf-call-iptables
#     - net.bridge.bridge-nf-call-ip6tables
#   when: >
#     ansible_distribution != 'Debian'
#     or ansible_distribution_major_version | int < 10

